### ISSUE TITLE
ssh connection

### ISSUE THREAD

**Issue by empereira** [leokuan2021/proxmox-k8s-cluster#1]
hi @leokuan2021 ,

How do you connect via ssh to k8s-master?

Does the connection need to be from within the proxmox server?

**Comment by leokuan2021** [comment]
The default address for the master node is 192.168.1.140. You can connect from any machine anywhere in your local network even from another subnet as long as a route exists, whether it's a VM or physical machine. It doesn't have to be another VM running on the Proxmox server.

**Comment by empereira** [comment]
hi @leokuan2021 

Thanks for the answer!! 

I had to change the network, because we work with vlanes in our infrastructure.

The following error occurs when trying to access via ssh for example the master node.

The access occurs with the public key of my pve2, correct?

```
root@pve2:~/proxmox-k8s-cluster# ssh -i ~/.ssh/id_rsa deploy@10.77.7.140
deploy@10.77.7.140: Permission denied (publickey).
```

**Comment by empereira** [comment]
hi @leokuan2021,

Now, started working. :)

Idk, ssh fail into master, but workers works.

Any clue?

```
null_resource.ansible_handover (local-exec): TASK [Gathering Facts] *********************************************************
null_resource.ansible_handover: Still creating... [2m0s elapsed]
null_resource.ansible_handover (local-exec): ok: [k8s-worker1]
null_resource.ansible_handover (local-exec): ok: [k8s-worker0]
null_resource.ansible_handover (local-exec): fatal: [k8s-master]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 110.77.7.140 port 22: Connection timed out", "unreachable": true}
```
